apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SecretMapping
metadata:
  creationTimestamp: null
spec:
  defaults:
    backendType: gcpSecretsManager
  secrets:
    - backendType: gcpSecretsManager
      gcpSecretsManager:
        projectId: phill
        uniquePrefix: collins
        version: 1
      mappings:
        - key: my-gsm-secret-name
          name: oauth
          property: value
      name: my-kubernetes-secret-name1
    - backendType: gcpSecretsManager
      mappings:
        - key: my-gsm-secret-name
          name: oauth
          property: value
      name: my-kubernetes-secret-name2