apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SecretMapping
spec:
  secrets:
  - name: lighthouse-oauth-token1
    backendType: vault
    mappings:
    - name: oauth
      key: secret/data/jx/pipelineUser
      property: token
  - name: lighthouse-oauth-token2
    backendType: gsm
    mappings:
      - name: oauth
        key: secret/data/jx/pipelineUser
        property: token

  defaultBackendType: vault
