apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  cluster:
    clusterName: mycluster
    project: myproject
    provider: gke
  ingress:
    domain: "defaultdomain.com"
    externalDNS: false
    namespaceSubDomain: ""
  vault: {}
