apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: mycluster
    environmentGitOwner: myowner
    gitKind: github
    gitName: github
    gitServer: https://github.com
    project: myproject
    provider: gke
    registry: gcr.io
    zone: europe-west2-b
  environments:
  - key: dev
    repository: jx-cluster-dev
  - key: staging
  - key: production
  ingress:
    domain: 34.105.246.143.xip.io
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: true
  pipelineUser:
    username: jstrachan
  repository: nexus
  secretStorage: gsm
  webhook: lighthouse
