filepath: ""
bases:
- environments.yaml
repositories:
- name: jenkins-x
  url: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- name: external-secrets
  url: https://godaddy.github.io/kubernetes-external-secrets
- name: jx-labs
  url: https://storage.googleapis.com/jenkinsxio-labs-private/charts
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: banzaicloud-stable
  url: https://kubernetes-charts.banzaicloud.com
releases:
- chart: jenkins-x/jxboot-helmfile-resources
  version: 0.0.268
  name: jxboot-helmfile-resources
  namespace: jx
  values:
  - versionStream/apps/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
- chart: external-secrets/kubernetes-external-secrets
  version: 4.0.0
  name: kubernetes-external-secrets
  namespace: vault-infra
  values:
  - versionStream/apps/external-secrets/kubernetes-external-secrets/values.yaml.gotmpl
- chart: jx-labs/jenkins-x-crds
  version: 0.0.7
  name: jenkins-x-crds
  namespace: jx
  values:
  - versionStream/apps/jx-labs/jenkins-x-crds/values.yaml
- chart: stable/nginx-ingress
  version: 1.39.1
  name: nginx-ingress
  namespace: nginx
  values:
  - versionStream/apps/stable/nginx-ingress/values.yaml.gotmpl
- chart: jenkins-x/tekton
  version: 0.0.56
  name: tekton
  namespace: jx
  values:
  - versionStream/apps/jenkins-x/tekton/values.yaml.gotmpl
- chart: jenkins-x/lighthouse
  version: 0.0.683
  name: lighthouse
  namespace: jx
  values:
  - versionStream/apps/jenkins-x/lighthouse/values.yaml.gotmpl
- chart: jenkins-x/nexus
  version: 0.1.30
  name: nexus
  namespace: jx
  values:
  - versionStream/apps/jenkins-x/nexus/values.yaml.gotmpl
- chart: jenkins-x/chartmuseum
  version: 1.1.7
  name: chartmuseum
  namespace: jx
  values:
  - versionStream/apps/jenkins-x/chartmuseum/values.yaml.gotmpl
- chart: banzaicloud-stable/vault-operator
  version: 1.3.0
  name: vault-operator
  namespace: vault-infra
- chart: jx-labs/vault-instance
  name: vault-instance
  namespace: vault-infra
- chart: jx-labs/pusher-wave
  version: 1.0.0
  name: pusher-wave
  namespace: jx
templates: {}
missingFileHandler: ""
