
# generated by: jx gitops variables
export APP_NAME="jx-gitops"
export BRANCH_NAME="master"
export BUILD_NUMBER="1"
export DOCKER_REGISTRY="gcr.io"
export DOCKER_REGISTRY_ORG="jx-labs-infra"
export JX_CHART_REPOSITORY="http://jenkins-x-chartmuseum:8080"
export PIPELINE_KIND="release"
export REPO_NAME="jx-gitops"
export REPO_OWNER="jenkins-x"
