apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo/bucketrepo/charts/
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://acme.com
    provider: gke
    registry: gcr.io
  environments:
  - key: dev
  - key: staging
  - key: production
  ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  repository: nexus
  storage:
  - name: backup
    url: gs://old-mybackup-bucket
  - name: logs
    url: gs://old-logs-bucket
  - name: reports
    url: gs://old-reports-bucket
  - name: repository
    url: gs://old-repo-bucket
  secretStorage: vault
  vault: {}
  webhook: lighthouse
