filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx
repositories:
- name: jxgh
  url: https://jenkins-x-charts.github.io/repo
releases:
- chart: jxgh/jxboot-helmfile-resources
  version: 1.0.64
  name: jxboot-helmfile-resources
  values:
  - ../../versionStream/charts/jxgh/jxboot-helmfile-resources/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/jenkins-x-crds
  version: 3.0.7
  name: jenkins-x-crds
  values:
  - ../../versionStream/charts/jxgh/jenkins-x-crds/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/jx-pipelines-visualizer
  version: 1.7.1
  name: jx-pipelines-visualizer
  values:
  - ../../versionStream/charts/jxgh/jx-pipelines-visualizer/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/jx-preview
  version: 0.0.183
  name: jx-preview
  values:
  - jx-values.yaml
- chart: jxgh/lighthouse
  version: 1.1.10
  name: lighthouse
  labels:
    version.jenkins-x.io: lock
  values:
  - ../../versionStream/charts/jxgh/lighthouse/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/bucketrepo
  version: 0.1.65
  name: bucketrepo
  values:
  - ../../versionStream/charts/jxgh/bucketrepo/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/jx-build-controller
  version: 0.3.3
  name: jx-build-controller
  labels:
    values.jenkins-x.io: lock
- chart: jxgh/local-external-secrets
  version: 0.0.13
  name: local-external-secrets
  values:
  - jx-values.yaml
- chart: jxgh/jx-kh-check
  version: 0.0.56
  name: health-checks-jx
  values:
  - ../../versionStream/charts/jxgh/health-checks-jx/values.yaml.gotmpl
  - jx-values.yaml
templates: {}
renderedvalues: {}
