apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SourceConfig
spec:
  groups:
  - owner: jenkins-x
    provider: https://github.com
    providerKind: github
    providerName: github
    repositories:
      - name: jx-cli
      - name: jx-gitops
  - owner: mygitlaborg
    provider: https://mygitlab.com
    providerKind: gitlab
    providerName: mygitlab
    repositories:
      - name: somegitlab
  - owner: jx-gitlab-test
    provider: https://gitlab.com
    providerKind: gitlab
    repositories:
    - name: cluster/gitlab-import-test-1
    - name: cluster/gitlab-import-test-2
    scheduler: in-repo

  scheduler: cheese
