apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    clusterName: bdd-boot
    environmentGitOwner: jenkins-x-bot-test
    project: jenkins-x-bdd3
    provider: gke
    zone: europe-west1-c
  environments:
  - key: dev
  - key: staging
  - key: production
  ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  secretStorage: vault
  storage:
  - name: logs
    url: gs://jx-bdd-log-store-jxpr
  vault:
    disableURLDiscovery: true
  webhook: prow
