
# generated by: jx gitops pr variables
export PR_BASE_REF="main"
export PR_BASE_SHA="fakesha1234"
export PR_HEAD_REF="my-branch"
export PR_HEAD_SHA="fakesha5678"
export PR_LABEL_ENV_STAGING="true"
export PR_LABEL_UPDATEBOT="true"
