apiVersion: v1
kind: Service
metadata:
  name: cheese
  annotations:
    chart: cheese
    beer: 'stella'
    wine: 'merlot'
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: cheese