apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: jstrachan-tekton3
    environmentGitOwner: jstrachan
    gitKind: github
    gitName: github
    gitServer: https://github.com
    gke:
      projectNumber: "688875092189"
    project: jenkins-x-labs-bdd1
    provider: gke
    registry: gcr.io
    zone: europe-west2-b
  environments:
  - key: dev
    owner: jstrachan
    repository: jx-demo-gke2-dev
  - key: staging
  - key: production
  ingress:
    domain: 34.89.8.12.nip.io
    externalDNS: false
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: true
  kuberhealthy: true
  pipelineUser:
    username: jstrachan
  repository: nexus
  secretStorage: gsm
  storage:
  - name: logs
    url: gs://logs-jstrachan-tekton3-d3ca9654053a
  - name: reports
    url: gs://reports-jstrachan-tekton3-d3ca9654053a
  - name: repository
    url: gs://repository-jstrachan-tekton3-d3ca9654053a
  vault: {}
  webhook: lighthouse
