apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SecretMapping
spec:
  defaults:
    backendType: vault
  secrets:
  - name: lighthouse-hmac-token
    mappings:
    - name: hmac
      key: secret/data/lighthouse/hmac
      property: token
  - name: lighthouse-oauth-token
    mappings:
    - name: oauth
      key: secret/data/jx/pipelineUser
      property: token
