filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx
repositories:
- name: jxgh
  url: https://jenkins-x-charts.github.io/repo
- name: dev
  url: http://bucketrepo/bucketrepo/charts/
releases:
- chart: jxgh/bucketrepo
  name: bucketrepo
  values:
  - jx-values.yaml
- chart: jxgh/lighthouse
  name: lighthouse
  values:
  - jx-values.yaml
- chart: dev/dummy
  version: 1.2.3
  name: dummy
  values:
  - jx-values.yaml
- chart: jxgh/jx-build-controller
  name: jx-build-controller
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
