filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx
repositories:
- name: jxgh
  url: https://jenkins-x-charts.github.io/repo
- name: doesnotexist
  url: https://storage.googleapis.com/chartmuseum.jenkins-x.io
releases:
- chart: jxgh/jxboot-helmfile-resources
  name: jxboot-helmfile-resources
  values:
  - jx-values.yaml
- chart: doesnotexist/bucketrepo
  name: bucketrepo
  values:
  - jx-values.yaml
- chart: jxgh/jx-build-controller
  name: jx-build-controller
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
