apiVersion: secret.jenkins-x.io/v1alpha1
kind: Schema
spec:
  objects:
  - name: jenkins-x-chartmuseum
    mandatory: true
    properties:
    - name: BASIC_AUTH_USER
      question: chartmuseum repository user name
      help: The username used to authenticate with chartmuseum (the helm repository)
      defaultValue: admin
    - name: BASIC_AUTH_PASS
      question: chartmuseum repository password
      help: The password to authenticate with the chartmuseum (the helm repository)
      minLength: 5
      maxLength: 41
      generator: password
