# Source: lighthouse/templates/lighthousejobs-crd.yaml
apiVersion: apiextensions.k8s.io/v1beta2
kind: CustomResourceDefinition
metadata:
  name: lighthousejobs2.lighthouse.jenkins.io
spec:
  group: lighthouse.jenkins.io
  names:
    kind: LighthouseJob
    singular: lighthousejob
    plural: lighthousejobs
    shortNames:
      - lhjob
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
