# generated by: jx gitops variables
export APP_NAME="myrepo"
export BRANCH_NAME="PR-23"
export DOCKER_REGISTRY="my-registry.com"
export DOCKER_REGISTRY_ORG="myowner"
export JX_CHART_REPOSITORY="http://bucketrepo/bucketrepo/charts/"
export REPO_NAME="myrepo"
export REPO_OWNER="myowner"