filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: nginx
repositories:
- name: stable
  url: https://charts.helm.sh/stable
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
releases:
- chart: ingress-nginx/ingress-nginx
  version: 3.12.0
  name: nginx-ingress
  values:
  - ../../versionStream/charts/ingress-nginx/ingress-nginx/values.yaml.gotmpl
  - jx-values.yaml
templates: {}
renderedvalues: {}
