filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: nginx
repositories:
- name: stable
  url: https://charts.helm.sh/stable
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
templates: {}
renderedvalues: {}
