filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx
repositories:
- name: jxgh
  url: https://jenkins-x-charts.github.io/repo
releases:
- chart: jxgh/lighthouse
  version: 0.0.628
  name: lighthouse
  values:
  - jx-values.yaml
- chart: jxgh/jxboot-helmfile-resources
  name: jxboot-helmfile-resources
  values:
  - jx-values.yaml
- chart: jxgh/jx-preview
  name: jx-preview
  values:
  - ../../jx-values.yaml
  - jx-values.yaml
- chart: jxgh/jenkins-x-crds
  name: jenkins-x-crds
  values:
  - ../../versionStream/charts/jxgh/jenkins-x-crds/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/local-external-secrets
  name: local-external-secrets
  values:
  - jx-values.yaml
- chart: jxgh/jx-build-controller
  name: jx-build-controller
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
