filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: secret-infra
repositories:
- name: jxgh
  url: https://jenkins-x-charts.github.io/repo
releases:
- chart: jxgh/vault-instance
  name: vault-instance
  values:
  - jx-values.yaml
- chart: jxgh/pusher-wave
  name: pusher-wave
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
