- namespace: cert-manager
  path: helmfiles/cert-manager/helmfile.yaml
  releases:
  - apiVersion: v1
    appVersion: v1.1.0
    description: A Helm chart for cert-manager
    home: https://github.com/jetstack/cert-manager
    icon: https://raw.githubusercontent.com/jetstack/cert-manager/master/logo/logo.png
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    maintainers:
    - email: james@jetstack.io
      name: munnerz
    name: cert-manager
    repositoryName: jetstack
    repositoryUrl: https://charts.jetstack.io
    sources:
    - https://github.com/jetstack/cert-manager
    version: 1.1.0
- namespace: jx-production
  path: helmfiles/jx-production/helmfile.yaml
  releases:
  - apiVersion: v1
    applicationUrl: http://nodey560-jx-production.34.89.8.12.nip.io
    description: A Helm chart for Kubernetes
    icon: https://raw.githubusercontent.com/cdfoundation/artwork/master/jenkinsx/icon/color/jenkinsx-icon-color.png
    ingresses:
    - name: nodey560
      url: http://nodey560-jx-production.34.89.8.12.nip.io
    name: nodey560
    repositoryName: dev
    repositoryUrl: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    resourcePath: config-root/namespaces/jx-production/nodey560
    version: 0.0.2
- namespace: jx-staging
  path: helmfiles/jx-staging/helmfile.yaml
  releases:
  - apiVersion: v1
    applicationUrl: http://nodey560-jx-staging.34.89.8.12.nip.io
    description: A Helm chart for Kubernetes
    icon: https://raw.githubusercontent.com/cdfoundation/artwork/master/jenkinsx/icon/color/jenkinsx-icon-color.png
    ingresses:
    - name: nodey560
      url: http://nodey560-jx-staging.34.89.8.12.nip.io
    name: nodey560
    repositoryName: dev
    repositoryUrl: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    resourcePath: config-root/namespaces/jx-staging/nodey560
    version: 0.0.2
  - apiVersion: v1
    applicationUrl: http://nodey554-jx-staging.34.89.8.12.nip.io
    description: A Helm chart for Kubernetes
    icon: https://raw.githubusercontent.com/cdfoundation/artwork/master/jenkinsx/icon/color/jenkinsx-icon-color.png
    ingresses:
    - name: nodey554
      url: http://nodey554-jx-staging.34.89.8.12.nip.io
    name: nodey554
    repositoryName: dev
    repositoryUrl: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    resourcePath: config-root/namespaces/jx-staging/nodey554
    version: 1.0.27
- namespace: jx
  path: helmfiles/jx/helmfile.yaml
  releases:
  - annotations:
      category: DeveloperTools
    apiVersion: v2
    appVersion: 0.7.5
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    description: ExternalDNS is a Kubernetes addon that configures public DNS servers with information about exposed Kubernetes services to make them discoverable.
    home: https://github.com/bitnami/charts/tree/master/bitnami/external-dns
    icon: https://bitnami.com/assets/stacks/external-dns/img/external-dns-stack-110x117.png
    keywords:
    - external-dns
    - network
    - dns
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    name: external-dns
    repositoryName: bitnami
    repositoryUrl: https://charts.bitnami.com/bitnami
    sources:
    - https://github.com/kubernetes-sigs/external-dns
    - https://github.com/bitnami/bitnami-docker-external-dns
    - https://github.com/kubernetes-sigs/external-dns
    version: 4.5.0
  - apiVersion: v1
    description: Acme
    icon: https://avatars2.githubusercontent.com/u/35583233?s=200&v=4
    name: acme
    repositoryName: jx3
    repositoryUrl: https://storage.googleapis.com/jenkinsxio/charts
    version: 0.0.19
  - apiVersion: v1
    description: A Helm chart for the resources for JX Boot
    home: https://github.com/jenkins-x-charts/jxboot-helmfile-resources
    icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-website/master/images/logo/jenkinsx-icon-color.svg
    ingresses:
    - name: chartmuseum
      url: http://chartmuseum-jx.34.89.8.12.nip.io/
    - name: hook
      url: http://hook-jx.34.89.8.12.nip.io/hook
    - name: nexus
      url: http://nexus-jx.34.89.8.12.nip.io/
    name: jxboot-helmfile-resources
    repositoryName: jx3
    repositoryUrl: https://storage.googleapis.com/jenkinsxio/charts
    resourcePath: config-root/namespaces/jx/jxboot-helmfile-resources
    version: 1.0.40
  - apiVersion: v2
    appVersion: 3.0.5
    description: Custom Resource Definitions for Jenkins X
    icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/d273e09/images/go.png
    name: jenkins-x-crds
    repositoryName: jx3
    repositoryUrl: https://storage.googleapis.com/jenkinsxio/charts
    resourcePath: config-root/namespaces/jx/jenkins-x-crds
    version: 3.0.5
  - apiVersion: v1
    appVersion: latest
    applicationUrl: http://dashboard-jx.34.89.8.12.nip.io
    description: Web UI for Jenkins X, with a clear goal - visualize the pipelines - and their logs.
    home: https://github.com/jenkins-x/jx-pipelines-visualizer
    icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-website/master/images/logo/jenkinsx-icon-color.svg
    ingresses:
    - name: jx-pipelines-visualizer
      url: http://dashboard-jx.34.89.8.12.nip.io
    name: jx-pipelines-visualizer
    repositoryName: jx3
    repositoryUrl: https://storage.googleapis.com/jenkinsxio/charts
    resourcePath: config-root/namespaces/jx/jx-pipelines-visualizer
    sources:
    - https://github.com/jenkins-x/jx-pipelines-visualizer
    version: 1.1.11
  - apiVersion: v1
    description: |
      This chart installs the jx-preview CRD and garbagecollection job
    home: https://github.com/jenkins-x/jx-preview
    icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-website/master/images/logo/jenkinsx-icon-color.svg
    name: jx-preview
    repositoryName: jxgh
    repositoryUrl: https://jenkins-x-charts.github.io/repo
    resourcePath: config-root/namespaces/jx/jx-preview
    version: 0.0.168
  - apiVersion: v1
    appVersion: 0.0.939
    description: |
      This chart bootstraps installation of [Lighthouse](https://github.com/jenkins-x/lighthouse).
    home: https://github.com/jenkins-x/lighthouse
    icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-website/master/images/logo/jenkinsx-icon-color.svg
    name: lighthouse
    repositoryName: jenkins-x
    repositoryUrl: https://storage.googleapis.com/chartmuseum.jenkins-x.io
    resourcePath: config-root/namespaces/jx/lighthouse
    version: 0.0.939
  - apiVersion: v1
    description: A Helm chart for Kubernetes
    home: https://github.com/jenkins-x-charts/nexus
    icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/master/jenkins-x-platform/images/nexus.png
    name: nexus
    repositoryName: jenkins-x
    repositoryUrl: https://storage.googleapis.com/chartmuseum.jenkins-x.io
    resourcePath: config-root/namespaces/jx/nexus
    version: 0.1.37
  - apiVersion: v1
    appVersion: 0.12.0
    deprecated: true
    description: DEPRECATED Host your own Helm Chart Repository
    home: https://github.com/helm/chartmuseum
    icon: https://raw.githubusercontent.com/helm/chartmuseum/master/logo2.png
    keywords:
    - chartmuseum
    - helm
    - charts repo
    name: chartmuseum
    repositoryName: stable
    repositoryUrl: https://charts.helm.sh/stable
    resourcePath: config-root/namespaces/jx/chartmuseum
    version: 2.14.2
  - apiVersion: v2
    appVersion: 3.0.0
    description: Jenkins X next gen cloud CI / CD platform for Kubernetes
    home: https://jenkins-x.io/
    icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-website/master/images/logo/jenkinsx-icon-color.svg
    maintainers:
    - email: jenkins-x@googlegroups.com
      name: Jenkins X Team
    name: jx-build-controller
    repositoryName: jx3
    repositoryUrl: https://storage.googleapis.com/jenkinsxio/charts
    resourcePath: config-root/namespaces/jx/jx-build-controller
    sources:
    - https://github.com/jenkins-x-plugins/jx-build-controller
    version: 0.0.34
- namespace: nginx
  path: helmfiles/nginx/helmfile.yaml
  releases:
  - annotations:
      artifacthub.io/changes: |
        - Remove helm2 support and update docs
    apiVersion: v2
    appVersion: 0.41.2
    description: Ingress controller for Kubernetes using NGINX as a reverse proxy and load balancer
    home: https://github.com/kubernetes/ingress-nginx
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
    keywords:
    - ingress
    - nginx
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - name: ChiefAlexander
    name: ingress-nginx
    repositoryName: ingress-nginx
    repositoryUrl: https://kubernetes.github.io/ingress-nginx
    resourcePath: config-root/namespaces/nginx/ingress-nginx-nginx-ingress
    sources:
    - https://github.com/kubernetes/ingress-nginx
    type: application
    version: 3.12.0
- namespace: secret-infra
  path: helmfiles/secret-infra/helmfile.yaml
  releases:
  - apiVersion: v1
    appVersion: 6.3.0
    description: Kubernetes External Secrets CustomResourceDefinition
    home: https://github.com/external-secrets/kubernetes-external-secrets
    keywords:
    - kubernetes-external-secrets
    - secrets
    maintainers:
    - name: external-secrets
      url: https://github.com/external-secrets
    name: kubernetes-external-secrets
    repositoryName: external-secrets
    repositoryUrl: https://external-secrets.github.io/kubernetes-external-secrets
    resourcePath: config-root/namespaces/secret-infra/kubernetes-external-secrets
    sources:
    - https://github.com/external-secrets/kubernetes-external-secrets
    version: 6.3.0
  - apiVersion: v1
    appVersion: v0.4.0
    description: wave chart that runs on kubernetes
    home: https://github.com/pusher/wave
    keywords:
    - wave
    - kubernetes
    name: pusher-wave
    repositoryName: jx3
    repositoryUrl: https://storage.googleapis.com/jenkinsxio/charts
    resourcePath: config-root/namespaces/secret-infra/pusher-wave
    sources:
    - https://github.com/pusher/wave
    version: 0.4.16
- namespace: tekton-pipelines
  path: helmfiles/tekton-pipelines/helmfile.yaml
  releases:
  - apiVersion: v1
    appVersion: 0.21.0
    description: A Helm chart for Tekton Pipelines
    home: https://github.com/cdfoundation/tekton-helm-chart
    icon: https://avatars2.githubusercontent.com/u/47602533
    name: tekton-pipeline
    repositoryName: cdf
    repositoryUrl: https://cdfoundation.github.io/tekton-helm-chart
    resourcePath: config-root/namespaces/tekton-pipelines/tekton-pipeline
    version: 0.21.1
