# Source: jxboot-helmfile-resources/templates/default-scheduler.yaml
apiVersion: jenkins.io/v1
kind: Scheduler
metadata:
  name: default
spec:
  approve:
    issueRequired: false
    lgtmActsAsApprove: true
    requireSelfApproval: true
  merger:
    blockerLabel: ""
    maxGoroutines: 0
    merge_method: merge
    policy:
      fromBranchProtection: true
      optional-contexts: { }
      required-contexts: { }
      required-if-present-contexts: { }
      skipUnknownContexts: false
    prStatusBaseUrl: ""
    squashLabel: ""
    targetUrl: http://deck-jx.35.192.148.208.nip.io
  plugins:
    entries:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
  policy:
    protectTested: true
  postsubmits:
    entries:
      - agent: tekton
        branches:
          - master
        cluster: ""
        context: ""
        labels: { }
        max_concurrency: 0
        name: release
        report: false
        run_if_changed: ""
        skip_branches: [ ]
  presubmits:
    entries:
      - agent: tekton
        always_run: true
        branches: [ ]
        cluster: ""
        context: pr-build
        labels: { }
        max_concurrency: 0
        merge_method: ""
        name: pr-build
        optional: false
        policy:
          required_status_checks:
            contexts:
              - pr-build
        queries:
          - excluded_branches: { }
            included_branches: { }
            labels:
              entries:
                - approved
            milestone: ""
            missing_labels:
              - do-not-merge
              - do-not-merge/hold
              - do-not-merge/work-in-progress
              - needs-ok-to-test
              - needs-rebase
            review_approved_required: false
          - excluded_branches: { }
            included_branches: { }
            labels:
              entries:
                - updatebot
            milestone: ""
            missing_labels:
              - do-not-merge
              - do-not-merge/hold
              - do-not-merge/work-in-progress
              - needs-ok-to-test
              - needs-rebase
            review_approved_required: false
        report: true
        rerun_command: /test this
        run_if_changed: ""
        skip_branches: [ ]
        trigger: (?m)^/test( all| this),?(\s+|$)
  schedulerAgent:
    agent: tekton
  trigger:
    ignoreOkToTest: false
    joinOrgUrl: ""
    onlyOrgMembers: false
    trustedOrg: todo
  welcome:
    - message_template: Welcome