
# generated by: jx gitops pr variables
export PR_BASE_REF="main"
export PR_BASE_SHA="fakesha1234"
export PR_HEAD_REF="my-branch"
export PR_HEAD_SHA="fakesha5678"
export PR_LABEL_ENV_STAGING="true"
export PR_LABEL_SOME_LABEL="true"
export PR_LABEL_SOME_LABEL_WITH_RANDOM_CHAR="true"
export PR_LABEL_SOME_RANDOM_LABEL="true"
export PR_LABEL_SOME_SPECIAL_LABEL="true"
export PR_LABEL_UPDATEBOT="true"


# content from git...
export DOCKER_REGISTRY='something.else'
export DOCKER_REGISTRY_ORG='another'
export KANIKO_FLAGS='custom-stuff'
