filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: secret-infra
repositories:
- name: external-secrets
  url: https://external-secrets.github.io/kubernetes-external-secrets
releases:
- chart: external-secrets/kubernetes-external-secrets
  version: 4.0.0
  name: kubernetes-external-secrets
  values:
  - ../../values/kubernetes-external-secrets/values.yaml.gotmpl
  - jx-values.yaml
templates: {}
renderedvalues: {}
