apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SourceConfig
spec:
  groups:
  - owner: jenkins-x
    provider: https://github.com
    providerKind: github
    providerName: github
    repositories:
    - name: jx-cli
    - name: jx-gitops
  scheduler: cheese
