# Source: cert-manager/templates/cainjector-rbac.yaml
# leader election rules
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: cert-manager-cainjector:leaderelection
  namespace: cert-manager
  labels:
    app: cainjector
    app.kubernetes.io/name: cainjector
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: cert-manager-v0.13.1
  annotations:
    beer: 'stella'
    wine: 'merlot'
rules:
  - # Used for leader election by the controller
    # TODO: refine the permission to *just* the leader election configmap
    apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "update", "patch"]
