# generated by: jx gitops variables
export APP_NAME='myrepo'
export BRANCH_NAME='PR-23'
export BUILD_NUMBER='5'
export DOCKERFILE_PATH='Dockerfile'
export DOCKER_REGISTRY='ghcr.io'
export DOCKER_REGISTRY_ORG='myowner'
export JX_CHART_REPOSITORY='http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts'
export KANIKO_FLAGS='cheese'
export MINK_AS='tekton-bot'
export MINK_IMAGE='ghcr.io/myowner/myrepo:1.2.3'
export PIPELINE_KIND='pullrequest'
export PUSH_CONTAINER_REGISTRY='localhost:5000'
export REPO_NAME='myrepo'
export REPO_OWNER='MyOwner'
export VERSION='1.2.3'


# content from git...
export DOCKER_REGISTRY='something.else'
export DOCKER_REGISTRY_ORG='another'
export KANIKO_FLAGS='custom-stuff'