apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: jx-pipeline-release
      resources: {}
      timeout: 1h30m0s
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/go-plugin/release.yaml@versionStream
          name: ""
          resources: {}
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
          name: ""
          resources: {}
        - name: next-version
          resources:
            requests:
              cpu: 1600m
              memory: 1400Mi
        - name: jx-variables
          resources: {}
        - name: release-binary
          resources: {}
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/build-scan-push/build-scan-push.yaml@versionStream
          name: build-container
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/build-scan-push/build-scan-push.yaml@versionStream
          name: push-container
        - name: chart-docs
          resources: {}
        - name: release-chart
          resources: {}
        - name: changelog
          resources: {}
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/supply-chain-security/task.yaml@versionStream
          name: download-syft
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/supply-chain-security/task.yaml@versionStream
          name: build-and-push-sbom
          resources: {}
        - name: cleanup-image-tar
          image: alpine:3.16
          resources: {}
          script: |
            #!/bin/sh
            rm -f /workspace/source/image.tar
        - name: upload-binaries
          resources: {}
        - name: promote-release
          resources: {}
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 1h30m0s
status: {}
